apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-deploy
  labels:
    name : crud-deploy
    app : demo-crud-app # совпадает с другими подами всего контура
spec:
  replicas: 1
  selector:
    matchLabels:
      name: crud-app-pod
      app: demo-crud-app # совпадает с другими подами всего контура
  template:
    metadata:
      name: crud-app-pod
      labels:
        name : crud-app-pod
        app : demo-crud-app # совпадает с другими подами всего контура
    spec:
      restartPolicy: Always
      containers:
        - name : crud-app
          image: romanyakit/crud:v3