apiVersion: v1
kind: Service
metadata:
  name: crud-service
  labels:
    name : crud-service
    app : demo-crud-app # совпадает с другими подами всего контура
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
  selector:
    name : crud-app-pod
    app : demo-crud-app # совпадает с другими подами всего контура